### ISSUE TITLE
Missing CONTRIBUTING.md File in Repository

### ISSUE THREAD

**Issue by suhanipaliwal** [dashroshan/openvpn-wireguard-admin#13]
The repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

Could you please assign this issue to me under GSSOC 24.

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by dashroshan** [comment]
@IP80808080 assigned

**Comment by suhanipaliwal** [comment]
Could you please assign this issue to me as well because I was the one who raised this issue initially.

**Comment by IP80808080** [comment]
Hello Sir

I have submitted a pull request for issue #13, which includes a Contribution.md for better contributing understanding. I kindly request you to review the pull request
